name: Handle Form Submissions

on:
  repository_dispatch:
    types: [submit-form]

jobs:
  save-submission:
    runs-on: ubuntu-latest
    if: github.event.client_payload.secret == 'shenj!ang2025-secret'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Save submission to file
        run: |
          mkdir -p submissions
          echo '${{ github.event.client_payload.data }}' > submissions/${{ github.event.client_payload.filename }}

      - name: Commit and push
        run: |
          git config --global user.name 'form-bot'
          git config --global user.email 'form@ecustegame.top'
          git add submissions/
          git commit -m "Add submission ${{ github.event.client_payload.filename }}" || echo "Nothing to commit"
          git push
