name: Handle Form Submissions

on:
  repository_dispatch:
    types: [submit-form]

jobs:
  save-submission:
    runs-on: ubuntu-latest
    # 如果你想校验 secret，可加上:
    if: github.event.client_payload.secret == 'shenj!ang2025-secret'
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Create submissions folder
        run: mkdir -p submissions

      - name: Save form data
        run: echo '${{ github.event.client_payload.data }}' > submissions/${{ github.event.client_payload.filename }}

      - name: Commit and push
        run: |
          git config user.name 'form-bot'
          git config user.email 'bot@ecustegame.top'
          git add submissions/
          git commit -m "Add ${{ github.event.client_payload.filename }}" || echo "Nothing to commit"
          git push
